apiVersion: v1
kind: Secret
metadata:
  name: conexao-solidaria-secrets
  namespace: conexao-solidaria
type: Opaque
stringData:
  Jwt__SigningKey: "chave-de-desenvolvimento-conexao-solidaria-2026-min-32-chars"
  Aws__AccessKey: "test"
  Aws__SecretKey: "test"
  POSTGRES_PASSWORD: "postgres"
